name: Test Notepad

on:
  workflow_dispatch:

jobs:
  gui-test:
    runs-on: self-hosted
    env:
      ACTIONS_RUNNER_DISABLE_PROCESS_CLEANUP: true

    steps:
      - name: Open Notepad
        run: powershell Start-Process "notepad.exe"
