name: Test Run Notepad

on:
  workflow_dispatch:

jobs:
  open-notepad:
    runs-on: self-hosted

    steps:
      - name: Buka Notepad GUI
        shell: cmd
        run: |
          start "" "C:\Windows\System32\notepad.exe"
