name: Test Notepad

on:
  workflow_dispatch:

jobs:
  gui-test:
    runs-on: self-hosted

    steps:
      - name: Open Notepad
        shell: cmd
        run: |
          start "" "C:\Windows\System32\notepad.exe"
